spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 536314594368-ppddlcigaaouuje0s60hq3tqjqv453f9.apps.googleusercontent.com
            clientSecret: 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
            redirectUri: "http://localhost:2222/oauth2/callback/google"
            scope:
              - email
              - profile